<template>
  <div></div>
</template>

<script>
export default {
  data () {
    return {
      events: {
        1: {
          name: 'Lost Cargo',
          description: 'Grants a random amount of credits'
        },
        2: {
          name: 'System Overclock',
          description: 'Doubles credits per second generated by buildings'
        },
        3: {
          name: 'Power Clicker',
          description: 'Doubles credits per click'
        }
      }

    }
  },

  methods: {
    CreateNewEvent (eventData) {
      let GameArea = this.gameAreaDimensions
      let RandomLocationX = Math.floor(Math.random() * GameArea.right) + GameArea.left
      let RandomLocationY = Math.floor(Math.random() * GameArea.bottom) + GameArea.top

      console.log(eventData)
      console.log(RandomLocationX)
      console.log(RandomLocationY)
    }
  },

  computed: {
    gameAreaDimensions () {
      return document.querySelector('#game-area').getBoundingClientRect()
    }
  },

  created () {
    this.randomEvent = setInterval(() => {
      let eventID = Math.floor(Math.random() * this.events.length) + 1
      this.CreateNewEvent(this.events[eventID])
    }, 3000)
  }
}
</script>

<style scoped lang="scss">
</style>
